name: Fabric CD (client secret)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options: [DEV, PROD]
        default: DEV

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (SPN with client secret)
        uses: azure/login@v2
        with:
          # JSON: {"clientId":"<GUID>","clientSecret":"<SECRET>","tenantId":"<GUID>"}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python - <<'PY'
          import fabric_cicd, sys
          print("fabric-cicd:", getattr(fabric_cicd, "__version__", "unknown"))
          print("python:", sys.version)
          PY

      - name: Deploy to Fabric
        env:
          FABRIC_ENVIRONMENT:  ${{ inputs.environment }}
          FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}
          REPOSITORY_DIRECTORY: Fabric   # 👈 case-sensitive
          ITEMS_IN_SCOPE: Notebook,DataPipeline,Lakehouse,SemanticModel,Report,Warehouse
          ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG || 'false' }}
          UNPUBLISH_ORPHANS: ${{ secrets.UNPUBLISH_ORPHANS || 'false' }}
          PYTHONUNBUFFERED: "1"
        run: |
          python ./Fabric/.deploy/deploy.py
